### ISSUE TITLE
Discussion: Consider merging `@abgov/nx-dotnet` with `@nx-dotnet/core`

### ISSUE THREAD

**Issue by AgentEnder** [GovAlta/nx-tools#54]
Hey 👋 , I'm the author of the @nx-dotnet/core and was wondering if the `nx-dotnet` package in this workspace could be folded into `@nx-dotnet/core`?

If this was done, and any projects using `@abgov/nx-dotnet` were moved to use `@nx-dotnet/core`, they would be able to gain dep-graph, project inference, and target inference capabilities.

Looking into the current implementation on this repo, it looks like the only functionality that would need to be moved over is the "workspace" generator.

Let me know if there is any interest, or if there is none we can close this out. Adopting the single library would ease maintenance burden, and I have been keeping up with `nx` releases as I am one of the core contributors on Nx.

Thanks for the consideration!
Craigory

**Comment by tzuge** [comment]
Hi @AgentEnder, I would love to switch over to your more broadly utilized library. 
The workspace generator is used to configure dotnet workspace to be more consistent with nx conventions, e.g.: 
- tests/specs beside code
- build intermediates and outputs to monorepo root /tmp and /dist folders.

Is this already handled in nx-dotnet/core?

**Comment by AgentEnder** [comment]
Hmmm, some of that is covered. 

- test/specs in same project is pretty cool, I didn't really think that was feasible at the time. This parts not handled from nx-dotnet, but we could add it as a flag to the app/lib generator maybe? Something like `--use-inline-tests`
- nx-dotnet/core handles the artifacts -> `dist` output mapping, but I don't think it handles intermediates to `/tmp`. Since these are .gitignore'd anyways and not relevant for caching, I hadn't bothered. 

That existing `workspace` generator could probably be moved over to nx-dotnet, if we figured out some good docs for it.

**Comment by AgentEnder** [comment]
Here's a link to the existing docs for nx-dotnet, https://www.nx-dotnet.com/docs/core/.

**Comment by tzuge** [comment]
I'm going to get the deprecation underway on this side with docs pointing to nx-dotnet.
